name: webhook
on: [check_run, check_suite]

jobs:
  debug:
    name: _debug
    runs-on: ubuntu-latest
    steps:
    - name: context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
