on: push
name: hello
jobs:
  hello:
    name: hello
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: hello world
      uses: maguowei/actions/hello@master
      with:
        args: Hello World
