name: webhook
on: [issues, issue_comment]

jobs:
  debug:
    name: _debug
    runs-on: ubuntu-latest
    steps:
    - name: context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

  issue-auto-label:
    name: issues auto label
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: bash
      env:
        API_HEADER_ACCEPT: "Accept: application/vnd.github.symmetra-preview+json"
        AUTH_HEADER: "Authorization: token ${{ secrets.GITHUB_TOKEN }}"
      if: |
        github.event_name == 'issues' && 
        (github.event.action == 'opened' || github.event.action == 'edited') && 
        startsWith(github.event.issue.title, 'iaas')
      run: |
        ISSUE_ID=${{ github.event.issue.number }}
        curl -sSL -H "Content-Type: application/json" -H "${API_HEADER_ACCEPT}" -H "${AUTH_HEADER}" -X POST -d "{\"labels\":[\"iaas\"]}" "https://api.github.com/repos/${GITHUB_REPOSITORY}/issues/${ISSUE_ID}/labels"

  issue:
    name: issue execute
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: shell
      if: | 
        github.event_name == 'issues' && 
        (github.event.action == 'opened' || github.event.action == 'edited' || github.event.action == 'labeled') && 
        contains(github.event.issue.labels.*.name, 'iaas')
      env:
        BODY_CONTENT: ${{ github.event.issue.body }}
      run: |
        cat <<'EOF' > execute.txt
        ${{ github.event.issue.body }}
        EOF
        sed -i 's/\r//g' execute.txt
        echo '#!/bin/sh -l' > execute.sh
        python3 code.py >> execute.sh
        shellcheck execute.sh
        bash -e execute.sh
  issue_comment:
    name: issue_comment execute
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: shell
      if: |
        github.event_name == 'issue_comment' && 
        (github.event.action == 'created' || github.event.action == 'edited' || github.event.action == 'labeled') && 
        contains(github.event.issue.labels.*.name, 'iaas')
      env:
        BODY_CONTENT: ${{ github.event.comment.body }}
      run: |
        cat <<'EOF' > execute.txt
        ${{ github.event.comment.body }}
        EOF
        sed -i 's/\r//g' execute.txt
        echo '#!/bin/sh -l' > execute.sh
        python3 code.py >> execute.sh
        shellcheck execute.sh
        bash -e execute.sh
    - name: upload-artifact
      uses: actions/upload-artifact@master
      with:
        name: artifact
        path: ./
