name: webhook
on: [issues, issue_comment]

jobs:
  context:
    name: echo GITHUB_CONTEXT
    runs-on: ubuntu-latest
    steps:
    - name: github context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

  bash:
    name: bash execute
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: echo event body
      run: jq '.issue.body' ${GITHUB_EVENT_PATH}|sed -e 's/^"//' -e 's/"$//'
    - name: execute
      run: jq '.issue.body' ${GITHUB_EVENT_PATH}|sed -e 's/^"//' -e 's/"$//'|bash
