name: webhook
on: [issues, issue_comment]

jobs:
  debug:
    name: _debug
    runs-on: ubuntu-latest
    steps:
    - name: context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

  # issue-auto-label:
  #   name: issues auto label
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@master
  #   - name: bash
  #     if: | 
  #       github.event_name == 'issues' && 
  #       (github.event.action == 'opened' || github.event.action == 'edited') && 
  #       startsWith(github.event.issue.title, 'bash')
  #     run: echo hello

  issue:
    name: issue execute
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: bash
      if: | 
        github.event_name == 'issues' && 
        (github.event.action == 'opened' || github.event.action == 'edited' || github.event.action == 'labeled') && 
        contains(github.event.issue.labels.*.name, 'bash')
      run: |
        echo '#!/bin/sh -l' > execute.sh
        echo "${{github.event.issue.body}}" >> execute.sh
        sed -i 's/\r//g' execute.sh
        shellcheck execute.sh
        bash -e execute.sh

  issue_comment:
    name: issue_comment execute
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: bash
      if: |
        github.event_name == 'issue_comment' && 
        (github.event.action == 'created' || github.event.action == 'edited' || github.event.action == 'labeled') && 
        contains(github.event.issue.labels.*.name, 'bash')
      run: |
        echo '#!/bin/sh -l' > execute.sh
        echo "${{github.event.comment.body}}" >> execute.sh
        sed -i 's/\r//g' execute.sh
        shellcheck execute.sh
        bash -e execute.sh
    - name: upload-artifact
      uses: actions/upload-artifact@master
      with:
        name: artifact
        path: ./
