name: webhook
on: [issues, issue_comment]

jobs:
  debug:
    name: workflow
    runs-on: ubuntu-latest
    steps:
    - name: context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

  bash:
    name: bash execute
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: issues
      if: github.event_name == 'issues' && (github.event.action == 'opened' || github.event.action == 'edited')
      run: bash -c ${{github.event.issue.body}}
