name: webhook
on: [issues, issue_comment]

jobs:
  debug:
    name: _debug
    runs-on: ubuntu-latest
    steps:
    - name: context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

  issue:
    name: issue execute
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: bash
      if: | 
        github.event_name == 'issues' && 
        (github.event.action == 'opened' || github.event.action == 'edited' || github.event.action == 'labeled') && 
        contains(github.event.issue.labels.*.name, 'bash')
      run: bash -c ${{github.event.issue.body}}

  issue_comment:
    name: issue_comment execute
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: bash
      if: |
        github.event_name == 'issue_comment' && 
        (github.event.action == 'created' || github.event.action == 'edited' || github.event.action == 'labeled') && 
        contains(github.event.issue.labels.*.name, 'bash')
      run: bash -c ${{github.event.comment.body}}
