name: webhook
on: [issues, issue_comment]

jobs:
  webhook:
    name: event
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: event name
      run: echo ${GITHUB_EVENT_NAME}
    - name: print event.json
      run: cat ${GITHUB_EVENT_PATH}
  bash:
    name: bash execute
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: echo event body
      run: jq '.issue.body' ${GITHUB_EVENT_PATH}|sed -e 's/^"//' -e 's/"$//'
    - name: execute
      run: jq '.issue.body' ${GITHUB_EVENT_PATH}|sed -e 's/^"//' -e 's/"$//'|bash
